### ISSUE TITLE
🎉 Overall Webpage's To-Do List

### ISSUE THREAD

**Issue by FaerieCoder** [FaerieCoder/Personal-Portfolio#1]
## User Story 🧑🏽‍💻
**AS A** student learning to become a software developer
**I WANT** to create an online personal portfolio
**SO THAT** people can see my programming journey and achievements

## Acceptance Criteria 📜
- [ ] When the page is loaded the page presents your name, a recent photo or avatar, and links to sections about you, your work, and how to contact you

- [ ] When one of the links in the navigation is clicked then the UI scrolls to the corresponding section

- [ ] When viewing the section about your work then the section contains titled images of your applications

- [ ] When presented with your first application then that application's image should be larger in size than the others

- [ ] When images of the applications are clicked then the user is taken to that deployed application

- [ ] When the page is resized or viewed on various screens and devices then the layout is responsive and adapts to my viewport
